services:
  papper-chats-service-postgres:
    image: postgres:16.1-bullseye
    container_name: papper-chats-service-postgres
    restart: unless-stopped
    volumes:
      - papper-chats-service-postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${CHATS_SERVICE_POSTGRES_DB_NAME}
      - POSTGRES_USER=${CHATS_SERVICE_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${CHATS_SERVICE_POSTGRES_DB_PASSWORD}
    ports:
      - 8310:5432
    networks:
      - papper-chats-service-network
  papper-chats-service:
    build: chats_service
    container_name: papper-chats-service
    restart: unless-stopped
    volumes:
      - ./chats_service:/usr/src/chats_service
    env_file:
      - ./chats_service/.env
    ports:
      - 8300:8000
    depends_on:
      - papper-chats-service-postgres
    command: >
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/chats_service/uvicorn_logging.conf"
    networks:
      - papper-chats-service-network
      - papper-backend

volumes:
  papper-chats-service-postgres-volume:

networks:
  papper-chats-service-network:
    name: papper-chats-service-network
  papper-backend:
    name: papper-backend
    external: true
