version: '3.9'

services:
  microservice1:
    build: microservice1
    volumes:
      - ./microservice1:/usr/src/microservice1
    env_file:
      - .env
    ports:
      - ${HOST_PORT}:8000
    command: > 
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  db_data: